%YAML:1.0

#common parameters
image0_topic: "/camera/infra1/image_rect_raw"
image1_topic: "/camera/infra2/image_rect_raw"

cam0_calib: "left_rs.yaml"
cam1_calib: "right_rs.yaml"
image_width: 848
image_height: 480
   
# Extrinsic parameters.
body_T_cam0: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [ 0, 0, 1,-0.011739999987185,
        -1, 0, 0, 0.0444522500038147,
        0, 1, 0, -0.00510000018402934,
        0., 0., 0., 1. ]

body_T_cam1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [ 0, 0, 1,  -0.011739999987185,
        -1, 0, 0, -0.00552000012248755,
        0, 1, 0,  -0.00510000018402934,
        0., 0., 0., 1. ]



max_freq: 20                # max frequency of processing image 

#feature traker paprameters
max_cnt: 50                # max feature number in feature tracking
min_cnt: 20                 # min feature number in feature tracking
min_dist: 30                # min distance between two features 

translation_threshold: 0.05 # min translation to switch key frame
rotation_threshold: 0.05    # min rotation to switch key frame
feature_threshold: 50       # min tracking feature to switch key frame
flow_back: 1            # perform forward and backward optical flow to improve feature tracking accuracy

show_feature: 1           # show tracked features in the images



#    data: [ -1.0021770212322867e-03, 3.6313480322730518e-04,
#        9.9999943188700535e-01, 1.5285779565991807e-02,
#        -9.9999216342926500e-01, -3.8303422615924010e-03,
#        -1.0007788055728661e-03, -5.2435791444330505e-02,
#        3.8299766679101843e-03, -9.9999259827824449e-01,
#        3.6697063849344680e-04, 8.6931302450199057e-03, 0., 0., 0., 1. ]
#    data: [   0, -1.,0,  -0.5,
#              0, 0., -1., -0.0,
#              1., 0., 0., 0.0,
#              0.,0.,0.,1. ]

